#!/usr/bin/python

#from acabsl import send
from lib_sl import send
import time
import sys
t = 0
x = int(sys.argv[1])
y = int(sys.argv[2])


while 1:
    send(x,y,255,0,0,0)
    time.sleep(t)
    send(x,y,0,255,0,0)
    time.sleep(t)
    send(x,y,0,0,255,0)
    time.sleep(t)
    send(x,y,0,0,0,0)
    time.sleep(t)


