#!/bin/sh
python server/acabslrouter.py nosimulation 7000 5000 &
python server/acabslserver.py server/config-keller.py &
python animations/s-color4-faster.py --port=5000 --wallsizex=1 --wallsizey=12 &
python animations/enerystar.py --port 5000 --wallsizex=1 --wallsizey=12 &

screen -A -m -d -S schedulerkeller python scheduler.py playlist-keller 8001 12 2
