#!/bin/sh

./acabsimulator.py "Wall 0" 4000 $1 &
SIM_PID=$!

./server/acabslrouter.py server/simulation-config.py simulation &
RTR_PID=$!

echo Now you can send animations to the simulator. For example:
echo     $ animations/gameoflife.py
echo Press enter to stop the simulation.
read dummy

kill $SIM_PID
kill $RTR_PID
