#!/bin/sh
python server/acabslrouter.py server/config-cccamp15-village.py & #nosimulation 5000 6000 &
python server/acabslserver.py server/config-cccamp15-village.py &
#python animations/s-color4-faster.py --port=6000 &
#python animations/enerystar.py --port=6003 &

screen -A -m -d -S cccamp-scheduler python scheduler.py playlist-cccamp 6001 1 16
