#!/usr/bin/python

from acabsl import send
import time
import sys
t = 1
x = int(sys.argv[1])
y = int(sys.argv[2])


while 1:
    send(x,y,255,0,0,.5)
    time.sleep(t)
    send(x,y,0,255,0,.5)
    time.sleep(t)
    send(x,y,0,0,255,.5)
    time.sleep(t)
    send(x,y,0,0,0,0.5)
    time.sleep(t)


