#!/usr/bin/env python

import acabsl
import time
import sys
t = 1

acabsl.update()

def set_all(r,g,b):
    for w in range(acabsl.NOOFWALLS):
        for x in range(acabsl.WALLSIZEX):
            for y in range(acabsl.WALLSIZEY):
                acabsl.send(x,y,r,g,b,0,w)
    acabsl.update()

while 1:
    set_all(255,0,0)
    time.sleep(t)
    set_all(0,255,0)
    time.sleep(t)
    set_all(0,0,255)
    time.sleep(t)



