#!/usr/bin/python

from acabsl import send
import time
import sys
t = .3
wall = int(sys.argv[1])
x = int(sys.argv[2])
x = int(sys.argv[1])


while 1:
    send(wall,x,y,255,0,0,.1)
    time.sleep(t)
    send(wall,x,y,0,255,0,.1)
    time.sleep(t)
    send(wall,x,y,0,0,255,.1)
    time.sleep(t)
    send(wall,x,y,0,0,0,.1)
    time.sleep(t)


