#!/usr/bin/python

from acabsl import send
from acabsl import update
import acabsl

import time
import sys
t = .3
x = int(sys.argv[1])
y = int(sys.argv[2])
t = float(sys.argv[3])

acabsl.UDPHOST = "acab"
acabsl.UDPPORT = 6002

while 1:
    send(x,y,255,0,0,t)
    #update()
    time.sleep(t)
    send(x,y,0,255,0,t)
    #update()
    time.sleep(t)
    send(x,y,0,0,255,t)
    #update()
    time.sleep(t)
    send(x,y,0,0,0,t)
    #update()
    time.sleep(t)


