# 67
import lib_sl
import random
import time

cs = [[255,255,000,000,000,255],[000,255,255,255,000,000],[000,000,000,255,255,255]]

def rc():
  return random.randint(0,5)

def rid():
    return [random.randint(0,8),random.randint(0,6)]


while 1:
    lib_sl.speedfade(rid(),rc(),60)
    time.sleep(0.5)
    lib_sl.speedfade(rid(),rc(),60)
    time.sleep(0.5)
    lib_sl.speedfade(rid(),rc(),60)
    time.sleep(0.5)
    lib_sl.speedfade(rid(),rc(),60)
    time.sleep(0.5)
    lib_sl.speedfade(rid(),rc(),60)
    time.sleep(0.5)
    lib_sl.speedfade(rid(),rc(),60)
    time.sleep(0.5)
    lib_sl.speedfade(rid(),rc(),60)
    time.sleep(0.5)
    lib_sl.speedfade(rid(),rc(),60)
    time.sleep(0.5)
    lib_sl.speedfade(rid(),rc(),60)
    time.sleep(0.5)
    lib_sl.speedfade(rid(),rc(),60)
    time.sleep(0.5)
    lib_sl.speedfade(rid(),rc(),60)
    time.sleep(0.5)
    lib_sl.speedfade(rid(),rc(),60)
    time.sleep(0.5)
    lib_sl.speedfade(rid(),rc(),60)
    time.sleep(0.5)
    lib_sl.speedfade(rid(),rc(),60)
    time.sleep(0.5)
    lib_sl.speedfade(rid(),rc(),60)
    time.sleep(0.5)
    lib_sl.speedfade(rid(),rc(),60)
    time.sleep(0.5)
    lib_sl.speedfade(rid(),rc(),60)
    time.sleep(0.5)
    lib_sl.speedfade(rid(),rc(),60)
    time.sleep(0.5)
    lib_sl.speedfade(rid(),rc(),60)
    time.sleep(0.5)
    lib_sl.speedfade(rid(),rc(),60)
    time.sleep(0.5)
    lib_sl.speedfade(rid(),rc(),60)
    time.sleep(0.5)
    lib_sl.speedfade(rid(),rc(),60)
    time.sleep(0.5)
    lib_sl.speedfade(rid(),rc(),60)
    time.sleep(0.5)
    lib_sl.speedfade(rid(),rc(),60)
    time.sleep(0.5)
    lib_sl.speedfade(rid(),rc(),60)
    time.sleep(0.5)
    lib_sl.speedfade(rid(),rc(),60)
    time.sleep(0.5)
    lib_sl.speedfade(rid(),rc(),60)
    time.sleep(0.5)
    lib_sl.speedfade(rid(),rc(),60)
    time.sleep(0.5)
    lib_sl.speedfade(rid(),rc(),60)
    time.sleep(0.5)
    lib_sl.speedfade(rid(),rc(),60)
    time.sleep(0.5)
    lib_sl.speedfade(rid(),rc(),60)
    time.sleep(0.5)
    lib_sl.speedfade(rid(),rc(),60)
    time.sleep(0.5)
    lib_sl.speedfade(rid(),rc(),60)
    time.sleep(0.5)
    lib_sl.speedfade(rid(),rc(),60)
    time.sleep(0.5)
    lib_sl.speedfade(rid(),rc(),60)
    time.sleep(0.5)
    lib_sl.speedfade(rid(),rc(),60)
    time.sleep(0.5)
    lib_sl.speedfade(rid(),rc(),60)
    time.sleep(0.5)
    lib_sl.speedfade(rid(),rc(),60)
    time.sleep(0.5)
    lib_sl.speedfade(rid(),rc(),60)
    time.sleep(0.5)
    lib_sl.speedfade(rid(),rc(),60)
    time.sleep(0.5)
    lib_sl.speedfade(rid(),rc(),60)
    time.sleep(0.5)
    lib_sl.speedfade(rid(),rc(),60)
    time.sleep(0.5)
    lib_sl.speedfade(rid(),rc(),60)
    time.sleep(0.5)
    lib_sl.speedfade(rid(),rc(),60)
    time.sleep(0.5)
    lib_sl.speedfade(rid(),rc(),60)
    time.sleep(0.5)
    lib_sl.speedfade(rid(),rc(),60)
    time.sleep(0.5)
    lib_sl.speedfade(rid(),rc(),60)
    time.sleep(0.5)
    lib_sl.speedfade(rid(),rc(),60)
    time.sleep(0.5)
    lib_sl.speedfade(rid(),rc(),60)
    time.sleep(0.5)
    lib_sl.speedfade(rid(),rc(),60)
    time.sleep(0.5)
    lib_sl.speedfade(rid(),rc(),60)
    time.sleep(0.5)
    lib_sl.speedfade(rid(),rc(),60)
    time.sleep(0.5)
    lib_sl.speedfade(rid(),rc(),60)
    time.sleep(0.5)
    lib_sl.speedfade(rid(),rc(),60)
    time.sleep(0.5)
    lib_sl.speedfade(rid(),rc(),60)
    time.sleep(0.5)
    lib_sl.speedfade(rid(),rc(),60)
    time.sleep(0.5)
